
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: customer_orders_passthrough
      description: "Passthrough model for CUSTOMER_ORDERS"
      columns:
        - name: ID
        - name: NAME
        - name: STATUS

    - name: cust_ordr_passthrough
      description: "Passthrough model for CUST_ORDR"
      columns:
        - name: ID
        - name: NAME
        - name: STATUS

    - name: combined_orders
      description: "Combines CUSTOMER_ORDERS and CUST_ORDR"
      columns:
        - name: ID
        - name: NAME
        - name: STATUS

    - name: apexclass_transformation
      description: "Filters SF1_APEXCLASS for active rows"
      columns:
        - name: ID
        - name: NAME
        - name: STATUS

    - name: joined_orders_with_apexclass
      description: "Joins combined orders with SF1_APEXCLASS"
      columns:
        - name: ID
        - name: NAME
        - name: STATUS
        - name: APEXCLASS_ID
        - name: APEXCLASS_NAME

sources:
  - name: sf1
    database: ODS_CORE
    schema: SF1
    tables:
      - name: CUSTOMER_ORDERS
        description: "Customer Orders table"
        columns:
          - name: ID
          - name: NAME
          - name: STATUS

      - name: CUST_ORDR
        description: "Customer Orders duplicate table"
        columns:
          - name: ID
          - name: NAME
          - name: STATUS

      - name: SF1_APEXCLASS
        description: "Salesforce Apex Class metadata"
        columns:
          - name: APIVERSION
          - name: BODY
          - name: BODYCRC
          - name: CREATEDBYID
          - name: CREATEDDATE
          - name: ID
          - name: ISVALID
          - name: LASTMODIFIEDBYID
          - name: LASTMODIFIEDDATE
          - name: LENGTHWITHOUTCOMMENTS
          - name: MD_DYNAMIC_CHANGE_FLAG
          - name: MD_INSERT_DATE
          - name: MD_SOURCE
          - name: NAME
          - name: NAMESPACEPREFIX
          - name: STATUS
          - name: SYSTEMMODSTAMP
